#define UINT                            1
#define INT                             2
#define EQUAL                           3
#define BAR                             4
#define DOTS                            5
#define COMMA                           6
#define LBRACKET                        7
#define RBRACKET                        8
#define NEG                             9
#define MANY                           10
#define STRING                         11
#define CONSTIDENTIFIER                12
#define OR                             13
#define LCURL                          14
#define RCURL                          15
#define VARIDENTIFIER                  16
#define LEDGE                          17
#define REDGE                          18
#define CHOOSE                         19
#define MANY1                          20
#define SEPBY                          21
#define SEPBY1                         22
#define OPTIONAL                       23
#define REF                            24
#define LPAREN                         25
#define RPAREN                         26
