#define UINT                            1
#define INT                             2
#define EQUAL                           3
#define BAR                             4
#define DOTS                            5
#define COMMA                           6
#define LBRACKET                        7
#define RBRACKET                        8
#define NEG                             9
#define MANY                           10
#define STRING                         11
#define CONSTIDENTIFIER                12
#define VARIDENTIFIER                  13
#define LCURL                          14
#define RCURL                          15
#define LEDGE                          16
#define REDGE                          17
#define CHOOSE                         18
#define MANY1                          19
#define SEPBY                          20
#define SEPBY1                         21
#define OPTIONAL                       22
#define REF                            23
#define OR                             24
#define LPAREN                         25
#define RPAREN                         26
